### ISSUE TITLE
Typo in equal_float

### ISSUE THREAD

**Issue by stacymiller** [StepicOrg/stepic-common#1]
Here:
https://github.com/StepicOrg/stepic-common/blob/master/src/stepic_common/__init__.py#L20
should be
`abs(answer-output)` instead of `abs(reply-clue)`

**Comment by vyahhi** [comment]
fixed in https://github.com/StepicOrg/stepic-common/commit/74d9d25feabeb214d32e1fc2bb9460bfc560b227
